[General]
ScreenWidth="1920"
ScreenHeight="1080"
Font="Noto Sans"
FontSize="13"
RoundCorners="8"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText=""
BackgroundPlaceholder=""
Background="Backgrounds/custom.jpg"
BackgroundSpeed="1.0"
DimBackground="0.2"
CropBackground="true"
HeaderTextColor="#cdd6f4"
DateTextColor="#cdd6f4"
TimeTextColor="#cdd6f4"
FormBackgroundColor="#1e1e2e"
BackgroundColor="#1e1e2e"
DimBackgroundColor="#1e1e2e"
LoginFieldBackgroundColor="#313244"
PasswordFieldBackgroundColor="#313244"
LoginFieldTextColor="#cdd6f4"
PasswordFieldTextColor="#cdd6f4"
UserIconColor="#89b4fa"
PasswordIconColor="#89b4fa"
PlaceholderTextColor="#585b70"
WarningColor="#f38ba8"
LoginButtonTextColor="#1e1e2e"
LoginButtonBackgroundColor="#89b4fa"
SystemButtonsIconsColor="#cdd6f4"
SessionButtonTextColor="#cdd6f4"
VirtualKeyboardButtonTextColor="#cdd6f4"
DropdownTextColor="#1e1e2e"
DropdownSelectedBackgroundColor="#89b4fa"
DropdownBackgroundColor="#313244"
HighlightTextColor="#1e1e2e"
HighlightBackgroundColor="#89b4fa"
HighlightBorderColor="transparent"
HoverUserIconColor="#b4befe"
HoverPasswordIconColor="#b4befe"
HoverSystemButtonsIconsColor="#b4befe"
HoverSessionButtonTextColor="#b4befe"
HoverVirtualKeyboardButtonTextColor="#b4befe"
PartialBlur="true"
BlurMax="8"
Blur="2.0"
HaveFormBackground="true"
FormPosition="center"
VirtualKeyboardPosition="center"
HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
